name: ragadl
description: "A simple image downloader app for Ragalahari"
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
versionCode: 301 # update this version to 2264 when update version to 2.6.4
version: 3.0.1+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  dio: ^5.3.2
  path_provider: ^2.1.1
  permission_handler: ^12.0.0+1
  html: ^0.15.0
  cached_network_image: ^3.3.0
  photo_view: ^0.15.0
  url_launcher: ^6.1.7
  device_info_plus: ^11.4.0
  shimmer: ^3.0.0
  intl: ^0.20.2
  shared_preferences: ^2.2.2
  csv: ^6.0.0
  file_picker: ^8.0.0+1
  share_plus: ^7.2.2
  window_manager: ^0.3.9
  flutter_isolate: ^2.0.4
  flutter_riverpod: ^2.5.0
  awesome_notifications: ^0.10.1
  archive: ^3.6.1
  async: ^2.11.0
  image: ^4.1.3
  open_file: ^3.3.2
  smooth_page_indicator: ^1.1.0  # Navigation dots
  extended_image: ^8.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.14.1
  flutter_native_splash: ^2.4.1
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/data/Fetched_StarZone_Data.csv
    - assets/logo.png
    - assets/data/Fetched_Albums_StarZone.json

flutter_native_splash:
  color: "#ffffff"
  image: assets/logo.png
  android: true
  ios: true

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/logo.png"
  min_sdk_android: 21
  remove_alpha_ios: true